name: klinik_aurora_portal
description: "Simplifying healthcare management from scheduling to inventory, ensuring efficient clinic operations and superior patient care."
publish_to: "none"

version: 1.0.5+5

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  animate_do: ^4.2.0
  calendar_date_picker2: ^2.0.0
  cupertino_icons: ^1.0.2
  data_table_2: ^2.5.11
  dio: ^5.4.1
  dotted_border: ^2.1.0
  dropdown_button2: ^2.3.9
  easy_localization: ^3.0.7+1
  easy_stepper: ^0.8.3
  file_picker: ^10.1.2
  file_saver: ^0.3.1
  fl_chart: ^0.71.0
  fluttertoast: ^8.2.4
  flutter_animate: ^4.5.0
  flutter_easyloading: ^3.0.5
  flutter_rating_stars: ^1.1.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  flutter_typeahead: ^5.2.0
  font_awesome_flutter: ^10.7.0
  go_router: ^15.1.1
  google_fonts: ^6.2.1
  http_parser: ^4.0.2
  intl: ^0.20.2
  lottie: ^3.3.1
  package_info_plus: ^8.3.0
  path_provider: ^2.1.5
  provider: ^6.1.2
  pinput: ^5.0.0
  rive: ^0.13.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  sidebarx: ^0.17.1
  url_launcher: ^6.2.5
  hovering: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/lottie/
    - assets/riv/
    - assets/typography/
    - assets/icons/failed/
    - assets/icons/logo/
    - assets/icons/success/
    - assets/images/status/
    - assets/translations/
    - assets/typography/proxima/

  fonts:
    - family: Proxima
      fonts:
        - asset: assets/typography/proxima/Proxima-Nova-Regular.ttf
        - asset: assets/typography/proxima/Proxima-Nova-Extrabold.ttf
          weight: 900
        - asset: assets/typography/proxima/Proxima-Nova-Black.ttf
          weight: 800
        - asset: assets/typography/proxima/Proxima-Nova-Bold.ttf
          weight: 700
        - asset: assets/typography/proxima/Proxima-Nova-Semibold.ttf
          weight: 600
        - asset: assets/typography/proxima/Proxima-Nova-Medium.ttf
          weight: 500
        - asset: assets/typography/proxima/Proxima-Nova-Regular.ttf
          weight: 400
        - asset: assets/typography/proxima/Proxima-Nova-Light.ttf
          weight: 300
        - asset: assets/typography/proxima/Proxima-Nova-Thin.ttf
          weight: 200
